version: '3.3'
services:
  db:
    image: postgres:13.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: advertising
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgres

volumes:
  postgres: